[package]
name = "rprompt"
version = "1.0.3"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
description = "Prompt user input in console applications."
license = "Apache-2.0"
homepage = "https://github.com/conradkdotcom/rprompt"
repository = "https://github.com/conradkdotcom/rprompt"
documentation = "https://docs.rs/rprompt/"
readme = "README.md"
keywords = ["prompt", "readline"]
